#ifndef APOLLO_CONFIG_HPP_INCLUDED
#define APOLLO_CONFIG_HPP_INCLUDED APOLLO_CONFIG_HPP_INCLUDED

#define APOLLO_VERSION_MAJOR 0
#define APOLLO_VERSION_MINOR 0
#define APOLLO_VERSION_PATCH 0

#endif // APOLLO_CONFIG_HPP_INCLUDED
