#include <boost/config/stdlib/libstdcpp3.hpp>

// Let's hope for the best:
#undef BOOST_NO_CXX11_HDR_CONDITION_VARIABLE
#undef BOOST_NO_CXX11_HDR_FORWARD_LIST
#undef BOOST_NO_CXX11_HDR_INITIALIZER_LIST
#undef BOOST_NO_CXX11_HDR_MUTEX
#undef BOOST_NO_CXX11_HDR_RATIO
#undef BOOST_NO_CXX11_HDR_SYSTEM_ERROR
#undef BOOST_NO_CXX11_SMART_PTR
