#ifndef LUABIND_CONFIG_HPP_INCLUDED
#define LUABIND_CONFIG_HPP_INCLUDED LUABIND_CONFIG_HPP_INCLUDED

#define CPPLUA_VERSION_MAJOR 0
#define CPPLUA_VERSION_MINOR 0
#define CPPLUA_VERSION_PATCH 0

#ifndef CPPLUA_MAX_ARITY
#   define CPPLUA_MAX_ARITY 5
#endif


#endif // LUABIND_CONFIG_HPP_INCLUDED
